openapi: 3.0.1
info:
  title: Currency
  version: 0.1.0
servers:
  - url: '{server}:{port}/currency'
    variables:
      server:
        default: http://localhost
      port:
        default: '9090'
paths:
  /rate:
    get:
      operationId: getRate
      parameters:
        - name: req
          in: query
          required: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConversionRequest'
      responses:
        '200':
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConversionResponse'
        '400':
          description: BadRequest
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorPayload'
        '404':
          description: NotFound
          content:
            application/json:
              schema:
                required:
                  - reason
                type: object
                properties:
                  reason:
                    type: string
components:
  schemas:
    ConversionRequest:
      required:
        - sourceCurrency
        - targetCurrency
      type: object
      properties:
        sourceCurrency:
          type: string
        targetCurrency:
          type: string
      additionalProperties: false
    ConversionResponse:
      required:
        - date
        - rate
      type: object
      properties:
        rate:
          type: number
          format: double
        date:
          type: string
      additionalProperties: false
    ErrorPayload:
      required:
        - message
        - method
        - path
        - reason
        - status
        - timestamp
      type: object
      properties:
        timestamp:
          type: string
        status:
          type: integer
          format: int64
        reason:
          type: string
        message:
          type: string
        path:
          type: string
        method:
          type: string
